twitter:
  oauth:
      consumer_key: 
      consumer_secret: 
      signature_method: "HMAC-SHA1"
      token: 
      token_secret: 
      version: "1.0"

  twitter_api_url: "https://api.twitter.com/1.1/"