twitter:
  rooms:
    - asp_name: l3_422
      doors: [ d3_422 ]
      common_names:
        - "GDC 3.422"
        - "3.422"
        - "422"
        
    - asp_name: l3_420
      doors: [ d3_420 ]
      common_names:
        - "GDC 3.420"
        - "3.420"
        - "420"

    - asp_name: l3_408
      doors: [ d3_408 ]
      common_names:
        - "GDC 3.408"
        - "3.408"
        - "408"

    - asp_name: l3_424
      common_names:
        - "GDC 3.424"
        - "3.424"
        - "424"
      
    - asp_name: l3_406
      common_names:
        - "GDC 3.406"
        - "3.406"
        - "406"
      
    - asp_name: l3_400
      common_names:
        - "GDC 3.400"
        - "3.400"
        - "400"
      
    - asp_name: l3_402
      doors: [ d3_402 ]
      common_names:
        - "GDC 3.402"
        - "3.402"
        - "402"
      
    - asp_name: l3_516
      doors: [ d3_516 ]
      common_names:
        - "GDC 3.516"
        - "3.516"
        - "516"
      
    - asp_name: l3_514
      common_names:
        - "GDC 3.514"
        - "3.514"
        - "514"
    
    - asp_name: l3_418
      doors: [ d3_418 ]
      common_names:
        - "GDC 3.418"
        - "3.418"
        - "418"
      
    - asp_name: l3_512
      doors: [ d3_512 ]
      common_names:
        - "GDC 3.512"
        - "3.512"
        - "512"
      
    - asp_name: l3_510
      doors: [ d3_510 ]
      common_names:
        - "GDC 3.510"
        - "3.510"
        - "510"
      
    - asp_name: l3_426
      common_names:
        - "GDC 3.426"
        - "3.426"
        - "426"
      
    - asp_name: l3_518
      common_names:
        - "GDC 3.518"
        - "3.518"
        - "518"
      
    - asp_name: l3_428
      common_names:
        - "GDC 3.428"
        - "3.428"
        - "428"
      
    - asp_name: l3_404
      doors: [ d3_404 ]
      common_names:
        - "GDC 3.404"
        - "3.404"
        - "404"
      
    - asp_name: l3_430
      doors: [ d3_430 ]
      common_names:
        - "GDC 3.430"
        - "3.430"
        - "430"
      
    - asp_name: l3_402
      doors: [ d3_402 ]
      common_names:
        - "GDC 3.402"
        - "3.402"
        - "402"
      
    - asp_name: l3_432
      doors: [ d3_432 ]
      common_names:
        - "GDC 3.432"
        - "3.432"
        - "432"
      
    - asp_name: l3_434
      doors: [ d3_434 ]
      common_names:
        - "GDC 3.434"
        - "3.434"
        - "434"
    
    - asp_name: l3_436
      doors: [ d3_436 ]
      common_names:
        - "GDC 3.436"
        - "3.436"
        - "436"
      
    - asp_name: l3_412
      common_names:
        - "GDC 3.412"
        - "3.412"
        - "412"
      
    - asp_name: l3_410
      common_names:
        - "GDC 3.410"
        - "3.410"
        - "410"
      
    - asp_name: l3_416
      doors: [ d3_416 ]
      common_names:
        - "GDC 3.416"
        - "3.416"
        - "416"
      
    - asp_name: l3_414a
      doors: [ d3_414a1, d3_414a2, d3_414a3 ]
      common_names:
        - "GDC 3.414a"
        - "GDC 3.414 a"
        - "3.414a"
        - "3.414 a"
        - "414a"
        - "414 a"
        - "the large lab"
        - "lab a"
        
    - asp_name: l3_414b
      doors: [ d3_414b1, d3_414b2, d3_414b3 ]
      common_names:
        - "GDC 3.414b"
        - "GDC 3.414 b"
        - "3.414b"
        - "3.414 b"
        - "414b"
        - "414 b"
        - "the main lab"
        - "the bwi lab"
        - "the robotics lab"
    
    - asp_name: l3_414
      doors: [ d3_414b3, d3_414a3 ]
      common_names:
        - "GDC 3.414"
        - "3.414"
        - "414"
        - "the middle room"
        - "the middle lab"
        - "the center lab"

    - asp_name: l3_502
      doors: [ d3_502 ]
      common_names:
        - "GDC 3.502"
        - "3.502"
        - "502"
    
    - asp_name: l3_504
      common_names:
        - "GDC 3.504"
        - "3.504"
        - "504"
          
    - asp_name: l3_506
      common_names:
        - "GDC 3.506"
        - "3.506"
        - "506"
      
    - asp_name: l3_500
      common_names:
        - "GDC 3.500"
        - "3.500"
        - "500"
          
    - asp_name: l3_508
      doors: [ d3_508 ]
      common_names:
        - "GDC 3.508"
        - "3.508"
        - "508"
      
    - asp_name: l3_520
      doors: [ d3_520 ]
      common_names:
        - "GDC 3.520"
        - "3.520"
        - "520"
      
    - asp_name: l3_200
      common_names:
        - "GDC 3.200"
        - "3.200"
        - "200"
      
    - asp_name: l3_300
      common_names:
        - "GDC 3.300"
        - "3.300"
        - "300"
      
    - asp_name: l3_302
      common_names:
        - "GDC 3.302"
        - "3.302"
        - "302"
      
    - asp_name: l3_303
      common_names:
        - "GDC 3.303"
        - "3.303"
        - "303"
    
    - asp_name: l3_250
      common_names:
        - "GDC 3.250"
        - "3.250"
        - "250"
